server:
  port: 8082

spring:
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: event-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3
    template:
      default-topic: movie-event-topic,user-event-topic,payment-event-topic

logging:
  level:
    root: INFO
    org.springframework.kafka: DEBUG