server:
  port: 8082

spring:
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3
      acks: "1"
      properties:
        spring.json.add.type.headers: false
        spring.json.value.default.type: org.example.model.PaymentEvent
        spring.json.type.mapping: |
          movieEvent:org.example.model.MovieEvent,
          paymentEvent:org.example.model.PaymentEvent,
          userEvent:org.example.model.UserEvent
    consumer:
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.value.default.type: org.example.model.MovieEvent
        spring.deserializer.key.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
    properties:
      spring.json.use.type.headers: false
    template:
      default-topic: movie-events
    listener:
      missing-topics-fatal: false
logging:
  level:
    root: INFO
    org.springframework.kafka: DEBUG
    org.example: DEBUG

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true