apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJVMjl5Wm05c09tZG9jRjl1YkVwc1JVOVJhblZQTVZVeGJVOVhhRlJaU2xCeVpEZGpjbTlJWWxVMFFWcFJXVUk9IgogICAgfQogIH0KfQo=
type: kubernetes.io/dockerconfigjson